use_sim_time: true

env_type: 0
robot_type: 1         # 0: A1
                      # 1: Go1
controller_type: 2    # 0: QP
                      # 1: Convex MPC
                      # 2: Quaternion MPC
kf_type: 0            # 0: no kf ( only available in Gazebo)
                      # 1: linear KF
                      # 2: EKF
terrain_adpt_state: 0 # 0: turn off terrain adaptation
                      # 1: turn on terrain adaptation

# Default foothold location in Relative frame
default_foot_pos_FL_x: 0.17
default_foot_pos_FL_y: 0.13
default_foot_pos_FL_z: -0.3

default_foot_pos_FR_x: 0.17
default_foot_pos_FR_y: -0.13
default_foot_pos_FR_z: -0.3

default_foot_pos_RL_x: -0.17
default_foot_pos_RL_y: 0.13
default_foot_pos_RL_z: -0.3

default_foot_pos_RR_x: -0.17
default_foot_pos_RR_y: -0.13
default_foot_pos_RR_z: -0.3

# Gait frequency
gait_freq: 2.2 # gait cycle per second

# Quaternion MPC parameters
mpc_update_period: 30.0
mpc_horizon: 10

w: 450.0 # quaternion weight

q_weights_0: 12.0  # x
q_weights_1: 12.0  # y
q_weights_2: 100.0  # z

q_weights_3: 0.0 # qw
q_weights_4: 0.0 # qx
q_weights_5: 0.0 # qy
q_weights_6: 0.0 # qz

q_weights_7: 7.0 # lin vel x
q_weights_8: 7.0 # lin vel y
q_weights_9: 10.0 # lin vel z

q_weights_10: 1.5 # ang vel x
q_weights_11: 6.0 # ang vel y
q_weights_12: 4.5 # ang vel z

r_weights_0: 0.000001
r_weights_1: 0.000001
r_weights_2: 0.000001

r_weights_3: 0.000001
r_weights_4: 0.000001
r_weights_5: 0.000001

r_weights_6: 0.000001
r_weights_7: 0.000001
r_weights_8: 0.000001

r_weights_9: 0.000001
r_weights_10: 0.000001
r_weights_11: 0.000001

mu: 0.7
fz_max: 100.0

# Swing leg control parameters
kp_hip: 20.0
kp_thigh: 20.0
kp_calf: 20.0

kd_hip: 1.5
kd_thigh: 1.5
kd_calf: 1.5

# Joystick settings
joystick_left_updown_axis:      1
joystick_left_horiz_axis:       0
joystick_right_updown_axis:     4
joystick_right_horiz_axis:      3
joystick_cross_left_right_axis: 6
joystick_cross_up_down_axis:    7

joystick_mode_switch_button:    0 # A
joystick_default_pos_button:    1 # B
sin_ang_vel_button:             3 # Y
joystick_exit_button:           4 # LB

# Joystick scaling
joystick_velx_scale: 0.5  # m/s
joystick_vely_scale: 0.1  # m/s
joystick_height_vel: 0.1  # m/s
joystick_max_height: 0.30  # m
joystick_min_height: 0.05  # m
joystick_yaw_rate_scale: 0.785  # rad/s
joystick_roll_rate_scale: 0.785 # rad/s
joystick_pitch_rate_scale: 0.785  # rad/s

# Contact detection related 
foot_sensor_max_value: 200.0
foot_sensor_min_value: 0.0
foot_sensor_ratio: 0.5

# Robot parameters
robot_mass: 12.84

trunk_inertia_xx: 0.0168128557
trunk_inertia_xy: 0.0
trunk_inertia_xz: 0.0
trunk_inertia_yz: 0.0
trunk_inertia_yy: 0.063009565
trunk_inertia_zz: 0.0716547275
